version: '3.4'
services:
  music-library-database:
    # build: ./database
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: xaivntaaj/music-library-database:2.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - db-data:/var/lib/mysql
  music-library-backend:
    # build: ./backend
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: xaivntaaj/music-library-backend:2.0
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - "music-library-database"
    command: >
      sh -c "flask db upgrade && gunicorn -b 0.0.0.0 app:app"
  music-library-frontend:
    # build: ./frontend
    # TODO Replace <docker hub username> with your Docker Hub account username and uncomment the line
    image: xaivntaaj/music-library-frontend:2.0
    ports:
      - 3000:3000
      - 80:80
      - 443:443
    depends_on:
      - "music-library-backend"
volumes:
  db-data:
  